name: Build Docker for run tests

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
      - 'requirements.txt'
  workflow_dispatch:


env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build local image for security scan
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: vmomot/python-test-container:latest
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "vmomot/python-test-container:latest"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: success()
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        if: success()
        with:
          context: .
          push: true
          tags: vmomot/python-test-container:latest

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        if: success()
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: your/image-to-test