name: E2E tests

on:
  push


env:
  allure-report-path: "allure-report"
  allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
  allure-token: ${{ secrets.ALLURE_TOKEN }}
  allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
  base_url: ${{ secrets.BASE_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: vmomot/python-test-container:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .env
        run: |
          echo "ALLURE_ENDPOINT=${{ env.allure-endpoint }}" >> .env
          echo "ALLURE_TOKEN=${{ env.allure-token }}" >> .env
          echo "ALLURE_PROJECT_ID=${{ env.allure-project-id }}" >> .env
          echo "BASE_URL=${{ env.base_url }}" >> .env
          source .env
      - name: Run tests
        run: allurectl watch --results ${{ env.allure-report-path }} -- python -m pytest --alluredir=${{ env.allure-report-path }}
