name: E2E tests

on:
  workflow_dispatch:


env:
  allure-report-path: "allure-report"
  allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
  allure-token: ${{ secrets.ALLURE_TOKEN }}
  allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
  base_url: ${{ secrets.BASE_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: vmomot/python-test-container:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .env
        run: |
          echo "BASE_URL=${{ env.base_url }}" >> .env
          dotenv .env
      - name: Setup Allure CTL
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.allure-endpoint }}
          allure-token: ${{ env.allure-token }}
          allure-project-id: ${{ env.allure-project-id }}
      - name: Run tests
        run: allurectl watch --results ${{ env.allure-report-path }} -- python -m pytest --alluredir=${{ env.allure-report-path }}
