name: E2E tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - test-ops
      - test-ops-with-docker

env:
  allure-report-path: "allure-report"
  allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
  allure-token: ${{ secrets.ALLURE_TOKEN }}
  allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
  base_url: ${{ secrets.BASE_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: myimage:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .env
        run: |
          echo "ALLURE_ENDPOINT=${{ secrets.ALLURE_ENDPOINT }}" > .env
          echo "ALLURE_TOKEN=${{ secrets.ALLURE_TOKEN }}" >> .env
          echo "ALLURE_PROJECT_ID=${{ secrets.ALLURE_PROJECT_ID }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          source .env
      - name: Run tests
        run: allurectl watch --results ${{ env.allure-report-path }} -- python -m pytest --alluredir=${{ env.allure-report-path }}
