name: E2E tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.27.1-focal
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest
  report:
    runs-on: ubuntu-latest
    needs: test
    id: allure-report
    steps:
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_DIR: ./public
      - name: Print report url
        if: always()
        run: echo ${{ allure-report.outputs.url }}
  pull-request-comment:
    runs-on: ubuntu-latest
    needs: [test, report]
    steps:
      - name: Add link to PR
        uses: mshick/add-pr-comment@v1
        with:
            message: |
              Allure report: ${{ allure-report.outputs.url }}
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            repo-token-user-login: 'github-actions[bot]'
        if: ${{ github.event_name }} == 'pull_request'