name: E2E tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - test-ops

env:
  allure-report-path: "allure-report"
  allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
  allure-token: ${{ secrets.ALLURE_TOKEN }}
  allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
  base_url: ${{ secrets.BASE_URL }}
  python-version: 3.10.1

jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: mcr.microsoft.com/playwright/python:v1.27.0-focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup .env
        run: |
          echo "BASE_URL=${{ env.base_url }}" > .env
      - name: Setup Allure
        uses: allure-framework/setup-allurectl@v1
        with:
            allure-endpoint: ${{ env.allure-endpoint }}
            allure-token: ${{ env.allure-token }}
            allure-project-id: ${{ env.allure-project-id }}
      - name: Run tests
        run: allurectl watch --results ${{ env.allure-report-path }} -- python -m pytest --alluredir=${{ env.allure-report-path }}
        env:
          ALLURE_RESULTS: build/allure-results
