name: Newman tests


on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:


jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Postman integration tests with Newman
        id: test
        uses: matt-ball/newman-action@v1.0.4
        with:
          collection: postman/postman_collection.json
          delayRequest: 1000
      - name: Notify that tests is success
        run: echo 'Tests success!'
        if: ${{ jobs.integration-tests.test.status }} == 'SUCCESS'