name: Owasp Scanners

on:
  push:
    branch: 'security-experiments'
  workflow_dispatch:

env:
  target: "https://itomychstudio.com/"

permissions:
  issues: write

jobs:
  zap_baseline_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZAP Scan
        uses: zaproxy/action-baseline@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ env.target }}
          cmd_options: '-a'
  zap_full_scan:
    runs-on: ubuntu-latest
    name: Full scan
    if: ${{ github.event.workflow_run.workflows.owasp.event_name }} == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ env.target }}
          cmd_options: '-a'
  zap_api_scan:
    runs-on: ubuntu-latest
    name: Api scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: ${{ env.target }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

#  k8s-sec-check:
#    runs-on: ubuntu-latest
#    steps:
#      # checkout master branch
#      - uses: actions/checkout@v2
#          with:
#            ref: master
#            path: master
#      # checkout PR branch
#      - uses: actions/checkout@v2
#          with:
#            path: candidate
#            ref: ${{ github.event.pull_request.head.sha }}
#      # pass the yamls directory to k8s-privilege-check git action
#      - name: Kubernetes Security Lint
#        uses: sysdiglabs/k8s-security-lint@v1.0.0
#        with:
#          sourceDir: '/master/yamls'
#          targetDir: '/candidate/yamls'
#      # evaluate escalation report
#      - name: Post Privilege Check
#        run: |
#          echo ${{ toJSON(steps.k8s_privilege_check.outputs.escalation_report) }}
#          # slack
#          # or other git action like adding another reviewer