name: Owasp Scanners

on:
  push:
    branch: 'security-experiments'
  workflow_dispatch:

env:
  target: "https://itomychstudio.com/"

permissions:
  issues: write

jobs:
  zap_baseline_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZAP Scan
        uses: zaproxy/action-baseline@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ env.target }}
          cmd_options: '-a'
  zap_full_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ env.target }}
          cmd_options: '-a'
  zap_api_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: ${{ env.target }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'